import { describe, expect, it } from "vitest";
import { readCssBundle } from "@/test/read-css-bundle";
import { cssRuleBody, readSource, root } from "./helpers";

const css = readCssBundle(root).css;
const foundationSource = readSource("src/app/styles/00-foundation.css");
const publicSource = readSource("src/app/styles/10-public.css");
const authenticatedShellSource = readSource("src/app/styles/20-authenticated-shell.css");
const recordsAndFormsSource = readSource("src/app/styles/30-records-and-forms.css");
const motionSource = readSource("src/app/styles/40-motion-and-feedback.css");
const journeySource = readSource("src/components/editorial/journey-showcase.tsx");
const landingMotionSource = readSource("src/components/editorial/landing-reveal.tsx");
const publicPageSource = readSource("src/app/page.tsx");
const expenseShareSource = readSource("src/components/expenses/expense-share-editor.tsx");
const repaymentAllocationSource = readSource("src/components/repayments/repayment-allocation-editor.tsx");
const taskPanelSource = readSource("src/components/app/task-panel.tsx");
const recordConfirmationSource = readSource("src/components/app/record-confirmation.tsx");

describe("Motion and feedback contract", () => {
  it("keeps ledger physicality decorative, restrained, and motion-safe", () => {
    expect(journeySource).toContain('data-journey-connectors="desktop"');
    expect(journeySource).toContain('aria-hidden="true"');
    for (const relationship of ["dinner-share", "taxi-share", "repayment-dinner-rani", "repayment-taxi-rani"]) expect(journeySource).toContain(`data-relationship="${relationship}"`);
    expect(journeySource).toContain("ledgerBranchPath");
    expect(journeySource).toContain("data-connector-anchor");
    expect(journeySource).toContain("frameElement.getBoundingClientRect()");
    expect(journeySource).toContain("reconcileConnectors");
    expect(journeySource).toContain("--journey-connector-share-progress");
    expect(journeySource).toContain("--journey-connector-repayment-progress");
    expect(publicSource).toContain("pointer-events: none");
    expect(publicSource).toContain("stroke-dasharray: 1");
    expect(publicSource).toContain(".journey-connectors { display: none;");
    expect(publicSource).toMatch(/@media \(min-width: 960px\) and \(min-height: 720px\)[\s\S]*?\.journey-connectors \{ display: block; \}/);
    expect(publicSource).toMatch(/@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.journey-connectors \{ display: none !important; \}/);
    expect(publicSource).toContain("perspective: 1200px;");
    expect(publicSource).toContain("transform: translateY(0) rotateX(0.75deg) rotateZ(-0.35deg)");
    expect(publicSource).toContain("rotateX(5deg) rotateZ(-1deg)");
    expect(publicSource).toContain("transform-origin: 50% 0;");
    expect(publicSource).not.toContain(".expense-proof__receipt:hover");
    expect(publicSource).not.toContain("mousemove");
    expect(publicSource).not.toContain("pointermove");
    expect(publicSource).toContain("perspective(1400px)");
    expect(publicSource).toContain("rotateX(calc(var(--ledger-handoff-depth");
    expect(publicSource).toContain(".public-home .hero__ledger-depth");
    expect(publicSource).toContain(".ledger-handoff__depth");
    expect(publicSource).toMatch(/\.ledger-handoff\s*\{[^}]*transform:\s*translate3d\([^}]+\);/);
    expect(publicSource).toMatch(/\.ledger-handoff__depth\s*\{[^}]*transform:\s*perspective\(1400px\)/);
    expect(landingMotionSource).toContain("--ledger-handoff-depth");
    expect(publicPageSource).toContain('className="hero__ledger-depth"');
    expect(publicPageSource).toContain('className="ledger-amount tabular-nums"');
    expect(publicPageSource.match(/ledger-amount/g)?.length).toBeGreaterThanOrEqual(7);
    expect(publicSource).toContain('font-feature-settings: "tnum"');
    expect(publicSource).toMatch(/@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.public-home \.hero__ledger-depth, \.ledger-handoff__depth \{ transform: none !important; \}/);
    expect(publicSource).toMatch(/@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.capability--receipt \.expense-proof \{ perspective: none; \}/);
  });

  it("keeps the public ledger handoff structural, coordinated, and motion-safe", () => {
    expect(publicPageSource).toContain("import { bandungStory }");
    expect(journeySource).toContain("bandungStory as scenario");
    expect(journeySource).toContain('from "./public-scenario"');
    expect(publicPageSource).toContain("data-ledger-handoff");
    expect(publicPageSource).toContain("Rani assigned");
    expect(publicPageSource).not.toContain("Rani&apos;s share");
    expect(publicPageSource).not.toContain("The same ledger continues");
    expect(publicPageSource).not.toContain('data-story-motion="handoff"');
    expect(publicSource).toContain("height: 30vh");
    expect(publicSource).not.toContain("min-height: 42vh");
    expect(publicSource).not.toContain(".story-motion--visible .ledger-handoff");
    expect(publicSource).not.toMatch(/ledger-handoff[^}]*520ms/);
    expect(publicSource).toContain("--ledger-handoff-width");
    expect(publicSource).toContain("--ledger-handoff-x");
    expect(publicSource).toContain("--ledger-handoff-y");
    expect(publicSource).toMatch(/\.ledger-handoff\s*\{[^}]*position:\s*absolute;/);
    expect(landingMotionSource).toContain("ledgerHandoffProgress(window.scrollY, start, travel)");
    expect(landingMotionSource).toContain("ledgerHandoffTravel(window.innerHeight)");
    expect(landingMotionSource).not.toContain("runway.offsetHeight");
    expect(landingMotionSource).toContain("heroLedger?.getBoundingClientRect()");
    expect(landingMotionSource).toContain("journeyFrame?.getBoundingClientRect()");
    expect(landingMotionSource).toContain('window.requestAnimationFrame(update)');
    expect(landingMotionSource).toContain('window.addEventListener("pageshow", onPageShow)');
    expect(landingMotionSource).not.toMatch(/setState|set[A-Z][A-Za-z]+\(progress/);
    expect(publicSource).toMatch(/@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.ledger-handoff-runway \{ display: none !important; \}/);
  });

  it("keeps the payoff amount visible first and resolves later states without a blank flow box", () => {
    expect(publicPageSource).toMatch(/className="payoff"[\s\S]*?<strong[^>]*data-payoff-state="amount"[^>]*>\{openBalance\}<\/strong>/);
    expect(publicPageSource).toMatch(/data-payoff-state="amount"[\s\S]*?data-payoff-state="row"[\s\S]*?data-payoff-state="cta"/);
    expect(landingMotionSource).toContain('[data-story-motion="finale"]');
    expect(landingMotionSource).toContain("--payoff-row-progress");
    expect(landingMotionSource).toContain("--payoff-cta-progress");
    expect(landingMotionSource).toContain(':not([data-story-motion="finale"])');
    expect(publicSource).not.toContain(".story-motion--visible .payoff > strong");
    expect(publicSource).toMatch(/\.payoff\s*\{[^}]*grid-template-rows:[^;}]*clamp\(/);
    expect(publicSource).toMatch(/\.payoff > strong\s*\{[^}]*grid-area:\s*2 \/ 1;/);
    expect(publicSource).toMatch(/\.payoff__row\s*\{[^}]*grid-area:\s*2 \/ 1;/);
    expect(publicSource).toMatch(/@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.payoff\s*\{\s*display:\s*block;/);
    expect(publicSource).toMatch(/@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.payoff__row\s*\{[^}]*margin-top:/);
  });

  it("scopes pinned share and repayment interpolation to persistent visual subtrees", () => {
    expect(publicSource).not.toMatch(/\.journey-sticky--pinned \.journey-expense-row:first-child \.journey-row/);
    expect(publicSource).not.toMatch(/\.journey-sticky--pinned \.journey-expense-row:nth-child\(2\) \.journey-row/);
    expect(publicSource).toContain(".journey-sticky--pinned .journey-expense-row:first-child .journey-expense-row__shares-reveal > .journey-row:first-child");
    expect(publicSource).toContain(".journey-sticky--pinned .journey-expense-row:first-child .journey-expense-row__shares-reveal > .journey-row:nth-child(2)");
    expect(publicSource).toContain(".journey-sticky--pinned .journey-expense-row:nth-child(2) .journey-expense-row__shares-reveal > .journey-row");
    expect(cssRuleBody(publicSource, ".journey-sticky--pinned .journey-repayment__allocation")).toMatch(/visibility:\s*visible;[\s\S]*opacity:\s*1;[\s\S]*transform:\s*none;/);
    expect(cssRuleBody(publicSource, ".journey-sticky--pinned .journey-repayment__allocation .journey-allocation__track span")).toContain("transform: scaleX(var(--journey-repayment-progress, 0));");
  });

  it("keeps requested motion primitives bounded, tokenized, and transition-safe", () => {
    expect(css).toContain("animation: row-in var(--motion-layout) var(--ease-product) both;");
    expect(css).not.toContain("row-insert");
    expect(css).toContain("@keyframes row-in {");
    expect(css).toContain("@keyframes result-in {");
    expect(css).toContain(".invite-form__result {");
    expect(css).toContain(".friend-share__result {");
    expect(css).toContain("transform-origin: left center;");
    expect(css).toContain("transition: transform var(--motion-state) var(--ease-product), background-color var(--motion-state) var(--ease-product);");
    expect(css).toMatch(/\.allocation-bar__fill\s*\{[\s\S]*?width:\s*100%;[\s\S]*?transform-origin:\s*left center;[\s\S]*?transition:\s*transform var\(--motion-state\)/);
    expect(css).toMatch(/@media \(prefers-reduced-motion: reduce\)\s*\{[\s\S]*?\.allocation-bar__fill\s*\{[\s\S]*?transform-origin:\s*left center;[\s\S]*?animation:\s*none !important;[\s\S]*?transition:\s*none !important;/);
    expect(css).not.toMatch(/\.allocation-bar__fill\s*\{[^}]*transform:\s*(?:none|scaleX\(1\))/);
    expect(css).toMatch(/\.task-panel--closing,[\s\S]*?transform:\s*none !important;/);
    expect(expenseShareSource).toContain("style={{ transform: `scaleX(${allocationProgress})` }}");
    expect(repaymentAllocationSource).toContain("style={{ transform: `scaleX(${allocationProgress})` }}");
    expect(expenseShareSource).not.toContain("style={{ width:");
    expect(repaymentAllocationSource).not.toContain("style={{ width:");
    expect(taskPanelSource).toContain("task-panel--closing");
    expect(taskPanelSource).toContain("onTransitionEnd");
    expect(taskPanelSource).not.toContain("onAnimationEnd");
    expect(recordConfirmationSource).toContain('"entering"');
    expect(recordConfirmationSource).toContain('"exiting"');
    expect(recordConfirmationSource).toContain("return null");
    expect(expenseShareSource).toContain("data-changed-revision");
    expect(expenseShareSource).not.toContain("setTimeout");
    expect(css).toContain(".changed-value__visual");
  });

  it("keeps interaction motion pointer-safe and tokenized", () => {
    expect(foundationSource).toMatch(/@media \(hover: hover\) and \(pointer: fine\)[\s\S]*?\.header-shell__nav a:hover::after/);
    expect(authenticatedShellSource).toMatch(/@media \(hover: hover\) and \(pointer: fine\)[\s\S]*?\.ledger-overview__friend-link:hover::after/);
    expect(recordsAndFormsSource).toMatch(/@media \(hover: hover\) and \(pointer: fine\)[\s\S]*?\.outing-row__edit:hover::after/);
    expect(foundationSource).toContain(".header-shell__nav a:focus-visible::after");
    expect(recordsAndFormsSource).toContain(".outing-row__edit:focus-visible::after");
    expect(motionSource).toMatch(/\.receipt-preview\s*\{[\s\S]*?height: 100dvh;/);
    expect(motionSource).toMatch(/\.receipt-preview\s*\{[\s\S]*?overflow: auto;[\s\S]*?overscroll-behavior: contain;/);
    expect(motionSource).toMatch(/\.receipt-preview__surface\s*\{[\s\S]*?max-height: calc\(100dvh - var\(--receipt-preview-gutter\) - var\(--receipt-preview-gutter\)\);[\s\S]*?overflow: hidden;/);
    expect(motionSource).toMatch(/\.receipt-preview__body\s*\{[\s\S]*?flex: 1 1 auto;[\s\S]*?min-height: 0;[\s\S]*?overflow: auto;/);
    expect(motionSource).toMatch(/\.receipt-preview__body img\s*\{[\s\S]*?max-width: 100%;[\s\S]*?max-height: min\(70dvh, 48rem\);[\s\S]*?object-fit: contain;/);
    expect(motionSource).toContain("receipt-preview--closing");
    expect(motionSource).toContain("@keyframes receipt-preview-out");
    expect(recordsAndFormsSource).toContain('.searchable-combobox__panel[data-placement="down"]');
    expect(recordsAndFormsSource).toContain('.searchable-combobox__panel[data-placement="up"]');
    expect(recordsAndFormsSource).toMatch(/@media \(prefers-reduced-motion: reduce\)[\s\S]*?\.searchable-combobox__panel\s*\{[\s\S]*?opacity: 1;[\s\S]*?transform: none;[\s\S]*?animation: none;/);
    expect(publicSource).toContain("animation: masked-hero-reveal var(--motion-reveal) var(--ease-emphasized) both;");
    expect(authenticatedShellSource).toContain("animation: field-reveal var(--motion-reveal) var(--ease-emphasized) both;");
    expect(publicSource).not.toContain("700ms cubic-bezier");
    expect(authenticatedShellSource).not.toContain("850ms");
    expect(publicSource).toContain(".action-link--primary:not(:disabled):active");
    expect(publicSource).toContain("transform: translateY(1px);");
    expect(motionSource).toContain(".action-link--primary:not(:disabled):active");
  });
});
