import type { GroupParticipant } from "@/server/groups";
import { createExternalParticipantAction, deleteExternalParticipantAction, removeGroupMemberAction, updateExternalParticipantAction, updateGroupMemberRoleAction } from "@/app/app/personal/groups/actions";

function roleLabel(role: string | null) {
  return role ? role[0]?.toUpperCase() + role.slice(1) : "";
}

export function GroupPeople({ groupId, participants, canManageParticipants, canManageRoles }: { groupId: string; participants: GroupParticipant[]; canManageParticipants: boolean; canManageRoles: boolean }) {
  const members = participants.filter((participant) => !participant.isExternal);
  const external = participants.filter((participant) => participant.isExternal);
  return <>
    <section className="group-detail__section" aria-labelledby="group-members-heading"><div className="group-section-heading"><div><p className="technical-label">REGISTERED</p><h2 id="group-members-heading">Members</h2></div><span className="technical-label">{members.length}</span></div><ul className="group-people__list">{members.map((member) => <li className="group-people__row" key={member.id}><span className="group-people__identity"><strong>{member.displayName}</strong><span>{roleLabel(member.role)}</span></span>{member.role !== "owner" && canManageRoles ? <form action={updateGroupMemberRoleAction.bind(null, groupId, member.userId ?? "")}><select name="role" defaultValue={member.role ?? "member"} aria-label={`Role for ${member.displayName}`}><option value="member">Member</option><option value="admin">Admin</option></select><button className="text-link" type="submit">Save role</button></form> : null}{member.role !== "owner" && ((canManageRoles) || (canManageParticipants && member.role === "member")) ? <form action={removeGroupMemberAction.bind(null, groupId, member.userId ?? "")}><button className="text-link" type="submit">Remove</button></form> : null}</li>)}</ul></section>
    <section className="group-detail__section" aria-labelledby="group-external-heading"><div className="group-section-heading"><div><p className="technical-label">LOCAL CONTEXT</p><h2 id="group-external-heading">External participants</h2></div><span className="technical-label">{external.length}</span></div>{external.length ? <ul className="group-people__list">{external.map((participant) => <li className="group-people__row group-people__row--external" key={participant.id}>{canManageParticipants ? <form className="group-external-form" action={updateExternalParticipantAction.bind(null, groupId, participant.id)}><div><input name="displayName" aria-label={`Name for ${participant.displayName}`} defaultValue={participant.displayName} /><input name="label" aria-label={`Label for ${participant.displayName}`} defaultValue={participant.label ?? ""} placeholder="Label (optional)" /></div><button className="text-link" type="submit">Save</button><button className="text-link" type="submit" formAction={deleteExternalParticipantAction.bind(null, groupId, participant.id)}>Remove</button></form> : <span className="group-people__identity"><strong>{participant.displayName}</strong>{participant.label ? <span>{participant.label}</span> : null}</span>}<span className="group-people__external-meta">External</span></li>)}</ul> : <p className="group-detail__empty">No external participants yet.</p>}{canManageParticipants ? <form className="group-external-create" action={createExternalParticipantAction.bind(null, groupId)}><input name="displayName" placeholder="Name" aria-label="External participant name" required /><input name="label" placeholder="Label (optional)" aria-label="External participant label" /><button className="action-link action-link--quiet" type="submit">Add external participant</button></form> : null}</section>
  </>;
}
